# Generated by Django 4.1.1 on 2023-02-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('symbol', models.CharField(max_length=1, verbose_name='Symbol')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In Stock')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products_module.currency', verbose_name='Currency')),
            ],
        ),
    ]
